askForName = "What is your name?"
askForBid = "What is your bid? $"
announceWinningBid = "The winning bid is $"
announceWinningBidder = "made by"
checkForNewBidder = "Is there a new bidder? Yes or No:"